/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.c
**     Project     : leds_ciclo
**     Processor   : MCF52233CAF60
**     Component   : MCF52233_80_LQFP
**     Version     : Component 01.003, Driver 01.06, CPU db: 3.00.000
**     Datasheet   : MCF52235RM Rev. 4, MCF52235RMAD Rev. 4, MCF52235DS Rev. 3, Family-Configs-52235
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2023-06-26, 18:11, # CodeGen: 43
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetIntLevel - void Cpu_SetIntLevel(byte Level);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.06
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

#include "LED1.h"
#include "LED2.h"
#include "LED3.h"
#include "LED4.h"
#include "DATO.h"
#include "CLOCK.h"
#include "EInt1.h"
#include "TI1.h"
#include "SERIAL.h"
#include "pinfoto.h"
#include "LCD1.h"
#include "LCD2.h"
#include "LCD3.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"
#include "IO_Map.h"


/* Global variables */
volatile word SR_reg;                  /* Current value of the SR register */
volatile byte SR_lock = 0x00;          /* Lock */
/*
** ===================================================================
**     Method      :  Cpu_Interrupt (component MCF52233_80_LQFP)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_Interrupt)
{
  /* This code can be changed using the CPU bean property "Build Options / Unhandled int code" */
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  asm (HALT);
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

/*
** ===================================================================
**     Method      :  Cpu_INT_SCM_SWTIInterrupt (component MCF52233_80_LQFP)
**
**     Description :
**         This ISR services the 'Core watchdog' interrupt.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_INT_SCM_SWTIInterrupt)
{
  Cpu_OnCoreWatchdogINT();
}

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MCF52233_80_LQFP)
**     Description :
**         Disables all maskable interrupts. This method sets the
**         interrupt level mask group in the SR register by value = 7.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MCF52233_80_LQFP)
**     Description :
**         Enables all maskable interrupts. This method sets the
**         interrupt level mask group in the SR register by value = 0.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetIntLevel (component MCF52233_80_LQFP)
**     Description :
**         Sets the interrupt level mask in the SR register. Interrupt
**         requests are inhibited for all priority levels less than or
**         equal to current level, except edge-sensitive level 7
**         request, which cannot be masked.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Level           - New interrupt priority level value.
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetIntLevel(byte Level)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  __initialize_hardware (component MCF52233_80_LQFP)
**
**     Description :
**         Initializes the whole system like timing, external bus, etc.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/*** !!! Here you can place your own code using property "User data declarations" on the build options tab. !!! ***/

void __initialize_hardware(void)
{
  extern uint32 __VECTOR_RAM[];


  /*** !!! Here you can place your own code before PE initialization using property "User code before PE initialization" on the build options tab. !!! ***/


  /* Initialize IPSBAR and validate it */
  asm {
    move.l  #0x40000001,d0
    move.l  d0,0x40000000
  }
  /* Initialize FLASHBAR */
  asm {
    move.l  #0x00000021,d0
    movec   d0,FLASHBAR
  }
  /* Initialize RAMBAR */
  asm {
    move.l  #0x20000221,d0
    movec   d0,RAMBAR
  }
  /* Initialize Vector Base Register (VBR) */
  asm {
    lea   __VECTOR_RAM,A0
    movec A0,VBR
    nop
  }


  /*** ### MCF52233CAF60 "Cpu" init code ... ***/
  /*** PE initialization code after reset ***/
  /* System clock initialization */
  /* CCHR: ??=0,??=0,??=0,??=0,??=0,CCHR=5 */
  setReg8(CCHR, 0x05U);                /* Set the predivider */ 
  /* SYNCR: LOLRE=0,MFD=5,LOCRE=0,RFD=0,LOCEN=0,DISCLK=0,FWKUP=1,??=0,??=0,CLKSRC=1,PLLMODE=1,PLLEN=1 */
  setReg16(SYNCR, 0x5027U);            /* Set the SYNCR register */ 
  while (!(SYNSR & SYNSR_LOCK_BITMASK)){} /* Wait until the PLL is locked. */
  /* ClockModule_LPCR: ??=0,??=0,??=0,??=0,LPD=0 */
  setReg8(ClockModule_LPCR, 0x00U);    /* Set the low power divider */ 
  /* RTCDR: RTCDF=0x017D783F */
  setReg32(RTCDR, 0x017D783FUL);       /* Set the RTC divider */ 
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code after PE initialization using property "User code after PE initialization" on the build options tab. !!! ***/

}

/*
** ===================================================================
**     Method      :  PE_low_level_init (component MCF52233_80_LQFP)
**
**     Description :
**         Initializes beans and provides common register initialization. 
**         The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Initialization of the SCM module */
  /* CWCR: CWE=0,CWRI=0,CWT=0,CWTA=0,CWTAVAL=1,CWTIF=1 */
  setReg8(CWCR, 0x03U);                 
  /* CWSR: CWSR=0x55 */
  setReg8(CWSR, 0x55U);                 
  /* CWSR: CWSR=0xAA */
  setReg8(CWSR, 0xAAU);                 
  /* CWCR: CWE=0,CWRI=0,CWT=0,CWTA=0,CWTAVAL=0,CWTIF=0 */
  setReg8(CWCR, 0x00U);                 
  /* MPARK: BCR24BIT=0 */
  clrReg32Bits(MPARK, 0x01000000UL);    
  /* DMAREQC: DMAC3=0,DMAC2=0,DMAC1=0,DMAC0=0 */
  clrReg32Bits(DMAREQC, 0xFFFFUL);      
  /* MPARK: M2_P_EN=0,M2_PRTY=2,M0_PRTY=0,FIXED=0,TIMEOUT=0,PRKLAST=0,LCKOUT_TIME=0 */
  clrSetReg32Bits(MPARK, 0x021C7F00UL, 0x00200000UL); 
  /* MPR: MPR=3 */
  clrSetReg8Bits(MPR, 0x0CU, 0x03U);    
  /* PACR0: LOCK1=0,ACCESS_CTRL1=0 */
  clrReg8Bits(PACR0, 0xF0U);            
  /* PACR1: LOCK0=0,ACCESS_CTRL0=0 */
  clrReg8Bits(PACR1, 0x0FU);            
  /* PACR2: LOCK1=0,ACCESS_CTRL1=0,LOCK0=0,ACCESS_CTRL0=0 */
  setReg8(PACR2, 0x00U);                
  /* PACR3: LOCK1=0,ACCESS_CTRL1=0 */
  clrReg8Bits(PACR3, 0xF0U);            
  /* PACR4: LOCK1=0,ACCESS_CTRL1=0,LOCK0=0,ACCESS_CTRL0=0 */
  setReg8(PACR4, 0x00U);                
  /* PACR6: LOCK1=0,ACCESS_CTRL1=0,LOCK0=0,ACCESS_CTRL0=0 */
  setReg8(PACR6, 0x00U);                
  /* PACR7: LOCK1=0,ACCESS_CTRL1=0,LOCK0=0,ACCESS_CTRL0=0 */
  setReg8(PACR7, 0x00U);                
  /* PACR8: LOCK1=0,ACCESS_CTRL1=0,LOCK0=0,ACCESS_CTRL0=0 */
  setReg8(PACR8, 0x00U);                
  /* GPACR0: LOCK=0,ACCESS_CTRL=0 */
  clrReg8Bits(GPACR0, 0x8FU);           
  /* GPACR1: LOCK=0,ACCESS_CTRL=0 */
  clrReg8Bits(GPACR1, 0x8FU);           
  /* Initialization of the PowerManagement module */
  /* PowerManagement_LPCR: LPMD=0 */
  clrReg8Bits(PowerManagement_LPCR, 0xC0U); 
  /* LPICR: ENBSTOP=0,XLPM_IPL=0 */
  clrReg8Bits(LPICR, 0xF0U);            
  /* PPMRH: CDRNGA=0,CDEPHY=0,CDCFM=0,CDFCAN=0,CDPWM=0,CDGPT=0,CDADC=0,CDPIT1=0,CDPIT0=0,CDEPORT=0,CDPORTS=0 */
  clrReg32Bits(PPMRH, 0x3F9BUL);        
  /* PPMRL: CDFEC0=0,CDINTC1=0,CDINTC0=0,CDTMR3=0,CDTMR2=0,CDTMR1=0,CDTMR0=0,CDRTC=0,CDQSPI=0,CDI2C=0,CDUART2=0,CDUART1=0,CDUART0=0,CDDMA=0,CDG=0 */
  clrReg32Bits(PPMRL, 0x0027F6F2UL);    
  /* IPSBMT: BME=1,BMT=0 */
  clrSetReg8Bits(IPSBMT, 0x07U, 0x08U); 
  /* Initialization of the ResetController module */
  /* ResetController_RCR: SOFTRST=0,FRCRSTOUT=0,??=0,LVDF=1,LVDIE=0,LVDRE=1,??=0,LVDE=1 */
  setReg8(ResetController_RCR, 0x15U);  
  /* Initialization of the CCM module */
  /* CCR: BME=1,BMT=0 */
  clrSetReg16Bits(CCR, 0x07U, 0x08U);   
  /* IMRL0: MASKALL=0 */
  clrReg32Bits(IMRL0, 0x01UL);         /* Disable masking of all interrupts of the INTC0 device */ 
  /* IMRL1: MASKALL=0 */
  clrReg32Bits(IMRL1, 0x01UL);         /* Disable masking of all interrupts of the INTC1 device */ 
  /* SCM_RAMBAR: BA=0x2000,??=0,??=0,??=0,??=0,??=0,??=0,BDE=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg32(SCM_RAMBAR, 0x20000200UL);   
  /* Common initialization of the CPU registers */
  /* PORTTC: PORTTC3=0,PORTTC2=0,PORTTC1=0,PORTTC0=0 */
  clrReg8Bits(PORTTC, 0x0FU);           
  /* DDRTC: DDRTC3=1,DDRTC2=1,DDRTC1=1,DDRTC0=1 */
  setReg8Bits(DDRTC, 0x0FU);            
  /* PTCPAR: PTCPAR3=0,PTCPAR2=0,PTCPAR1=0,PTCPAR0=0 */
  setReg8(PTCPAR, 0x00U);               
  /* PORTAN: PORTAN5=0,PORTAN4=0,PORTAN3=0,PORTAN2=0,PORTAN1=0 */
  clrReg8Bits(PORTAN, 0x3EU);           
  /* DDRAN: DDRAN5=1,DDRAN4=1,DDRAN3=1,DDRAN2=1,DDRAN1=1 */
  setReg8Bits(DDRAN, 0x3EU);            
  /* PANPAR: PANPAR5=0,PANPAR4=0,PANPAR3=0,PANPAR2=0,PANPAR1=0 */
  clrReg8Bits(PANPAR, 0x3EU);           
  /* EPDDR0: EPDD7=0 */
  clrReg8Bits(EPDDR0, 0x80U);           
  /* ICR045: IL=4,IP=3 */
  clrSetReg8Bits(ICR045, 0x1CU, 0x23U); 
  /* PUAPAR: PUAPAR1=1,PUAPAR0=1 */
  clrSetReg8Bits(PUAPAR, 0x0AU, 0x05U); 
  /* PORTUB: PORTUB2=0 */
  clrReg8Bits(PORTUB, 0x04U);           
  /* DDRUB: DDRUB2=1 */
  setReg8Bits(DDRUB, 0x04U);            
  /* PUBPAR: PUBPAR2=0 */
  clrReg8Bits(PUBPAR, 0x30U);           
  /* ICR008: IL=0,IP=0 */
  clrReg8Bits(ICR008, 0x3FU);           
  /* ICR048: IL=0,IP=0 */
  clrReg8Bits(ICR048, 0x3FU);           
  /* EPPAR0: EPPA7=1 */
  clrSetReg16Bits(EPPAR0, 0x8000U, 0x4000U); 
  /* PNQPAR: PNQPAR7=1 */
  clrSetReg16Bits(PNQPAR, 0x8000U, 0x4000U); 
  /* IMRL0: INT_MASK8=1,INT_MASK7=0 */
  clrSetReg32Bits(IMRL0, 0x80UL, 0x0100UL); 
  /* IMRH0: INT_MASK48=1,INT_MASK45=0 */
  clrSetReg32Bits(IMRH0, 0x2000UL, 0x00010000UL); 
  /* ### BitIO "LED1" init code ... */
  /* ### BitIO "LED2" init code ... */
  /* ### BitIO "LED3" init code ... */
  /* ### BitIO "LED4" init code ... */
  /* ### BitIO "DATO" init code ... */
  /* ### BitIO "CLOCK" init code ... */
  /* ### TimerInt "TI1" init code ... */
  TI1_Init();
  /* ### Asynchro serial "SERIAL" init code ... */
  SERIAL_Init();
  /* ### BitIO "pinfoto" init code ... */
  /* ### BitIO "LCD1" init code ... */
  /* ### BitIO "LCD2" init code ... */
  /* ### BitIO "LCD3" init code ... */
  /* Common peripheral initialization - ENABLE */
  /* EPFR0: EPF7=1 */
  setReg8Bits(EPFR0, 0x80U);            
  /* EPIER0: EPIE7=1 */
  setReg8Bits(EPIER0, 0x80U);           
  __EI(0);                             /* Enable interrupts of the given priority level */
}


/* END Cpu. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
